#include parent folder
import os, sys, inspect

currentdir = os.path.dirname(
    os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0, parentdir)

import numpy as np
import pytest
import jax

from src.domain import *


def test_Epot():
    pos = np.array([
        [1,1,1],
        [2,2,2],
        [3,3,3]
    ])
    
    E = VLJ(pos[0], pos[1]) + VLJ(pos[0], pos[2]) + VLJ(pos[1], pos[2])

    assert(Epot(pos) == E)


def test_minimize():
    domain = Domain()
    domain.fill(5, 9, 1)
    E_old = Epot(domain.pos)
    domain.minimizeEnergy()
    E_new = Epot(domain.pos)
    assert(E_new < E_old)  

"""

def test_read_write_to_file():
    # TODO fix unit test
    fileName = "out/unitTest_testFile"

    old_domain = Domain()
    old_domain.fill(5, 9, 1)
    old_domain.write_to_file(fileName, comment="generated by test_read_write_to_file(). Unimportant file")

    new_domain = Domain()
    new_domain.read_from_file(fileName)

    assert old_domain.pos.all() == new_domain.pos.all()
"""

if __name__ == "__main__":
    test_read_write_to_file()